site:
  title: Vulkan Docs Test
  start_page: vulkan-docs-test::index.adoc
content:
  sources: 
  - url: vulkan-tutorial
    branches: HEAD
    start_path: ./
  - url: vulkan-samples
    branches: HEAD
    start_path: ./
  - url: vulkan-guide
    branches: HEAD
    start_path: antora
  - url: vulkan-understanding
    branches: HEAD
    start_path: ./
  - url: vulkan-docs-test
    branches: HEAD
    start_path: ./    
ui: 
  bundle:
    url: ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - '@antora/lunr-extension'