site:
  title: Vulkan Docs Testbed
  start_page: spec::index.adoc
content:
  sources: 
  - url: vulkan-tutorial
    branches: HEAD
    start_path: antora
  - url: vulkan-samples
    branches: HEAD
    start_path: antora
  - url: vulkan-guide
    branches: HEAD
    start_path: antora
  - url: vulkan-docs
    branches: HEAD
    start_paths: antora/spec, antora/Features
  - url: GLSL
    branches: HEAD
    start_path: antora    
  # - url: vulkan-understanding
  #   branches: HEAD
  #   start_path: ./
ui: 
  bundle:
    url: ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
  - '@asciidoctor/tabs'  
antora:
  extensions:
  - '@antora/lunr-extension'